# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/autodata',
                'doc_host': 'https://clemenscremer.github.io',
                'git_url': 'https://github.com/clemenscremer/autodata',
                'lib_path': 'autodata'},
  'syms': {'autodata.core': {'autodata.core.foo': ('core.html#foo', 'autodata/core.py')}}}